### ISSUE TITLE
Bug: Postgres `Exception during reset or similar` errors

### ISSUE THREAD

**Issue by patheard** [cds-snc/scan-files#226]
# Summary
We're seeing the following non-user impacting [error](https://gcdigital.slack.com/archives/C03PA6DPFEG/p1660785114615749) sporadically for `/healthcheck` requests:
```python
[ERROR]	2022-08-18T01:10:21.366Z	dbc40eba-fde5-4cef-8b02-a52cab997d48	Exception during reset or similar
Traceback (most recent call last):
    File "/pymodules/sqlalchemy/pool/base.py", line 739, in _finalize_fairy
    fairy._reset(pool)
    File "/pymodules/sqlalchemy/pool/base.py", line 988, in _reset
    pool._dialect.do_rollback(self)
    File "/pymodules/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
    psycopg2.OperationalError: SSL connection has been closed unexpectedly
```
It's possible that it's related to this:
https://stackoverflow.com/questions/61361895/psycopg2-errors-idleintransactionsessiontimeout-terminating-connection-due-to-i

> The root cause is that you have database sessions that have started a transaction with BEGIN but are inactive longer than the PostgreSQL parameter idle_in_transaction_session_timeout

# Possible fix
Make sure the DB session is always closed:
```python
session = init_session()
    try:
        ... # business logic with other calls and raise-s
        session.commit() # optional
    finally:
        session.close()
```

**Comment by patheard** [comment]
Starting to see this error crop up again occasionally, so more investigation is needed.

**Comment by patheard** [comment]
Another possible fix, this time around keepalive args:
https://stackoverflow.com/a/67421581
